### ISSUE TITLE
"We ask you, humbly, to help." has white background

### ISSUE THREAD

**Issue by MangaD** [n0x-styles/wikipedia-dark#27]
The following CSS improved it for me.

```css
#frb-inline {
    background: #222;
}
.frb-legend, .frb-inline-close, .frb-inline-rml-form-close, .frb-inline-close:hover, .frb-inline-close:focus, .frb-inline-rml-form-close:hover, .frb-inline-rml-form-close:focus {
    color: #ededed;
}
```
